/*************************************************************************************************

Welcome to Baml! To use this generated code, please run one of the following:

$ npm install @boundaryml/baml
$ yarn add @boundaryml/baml
$ pnpm add @boundaryml/baml

*************************************************************************************************/

// This file was generated by BAML: do not edit it. Instead, edit the BAML
// files and re-generate this code.
//
/* eslint-disable */
// tslint:disable
// @ts-nocheck
// biome-ignore format: autogenerated code
'use server'

import { b } from '../index';
import type { Check, Checked  } from "../types";
import type { Image, Audio } from "@boundaryml/baml";

import type {  ContractorEstimate,  LineItem,  Milestone,  TimelineInfo } from "../types"

import type * as types from "../types"

/**
 * Regular BAML server actions that return direct responses.
 */

/**
 * Executes the "GenerateEstimate" BAML action.
 *
 * This server action calls the underlying BAML function "GenerateEstimate"
 * with the specified parameters.
 *
 * @param { string } project_name - Input parameter.
 * @param { string } description - Input parameter.
 * @param { string[] } requirements - Input parameter.
 *
 * @returns {Promise<ContractorEstimate>} A promise that resolves with the result of the action.
 */
export const GenerateEstimate = async (
  project_name: string,
  description: string,
  requirements: string[],
): Promise<ContractorEstimate> => {
  return b.GenerateEstimate(
    project_name,
    description,
    requirements,
  );
};