/*************************************************************************************************

Welcome to Baml! To use this generated code, please run one of the following:

$ npm install @boundaryml/baml
$ yarn add @boundaryml/baml
$ pnpm add @boundaryml/baml

*************************************************************************************************/

// This file was generated by BAML: do not edit it. Instead, edit the BAML
// files and re-generate this code.
//
/* eslint-disable */
// tslint:disable
// @ts-nocheck
// biome-ignore format: autogenerated code
'use server'

import { b } from '../index';
import type { Check, Checked  } from "../types";
import type { Image, Audio } from "@boundaryml/baml";

import type {  ContractorEstimate,  LineItem,  Milestone,  TimelineInfo } from "../types"

import type * as types from "../types"

/**
 * Streaming BAML server actions that return ReadableStreams.
 */

/**
 * Executes the streaming variant of the "GenerateEstimate" BAML action.
 *
 * This action initiates a streaming response by calling the corresponding
 * BAML stream function. The returned stream yields incremental updates.
 *
 * @param { string } project_name - Input parameter.
 * @param { string } description - Input parameter.
 * @param { string[] } requirements - Input parameter.
 *
 * @returns {ReadableStream<Uint8Array>} A stream that yields incremental updates from the action.
 */
export const GenerateEstimate = async (
  project_name: string,
  description: string,
  requirements: string[],
): Promise<ReadableStream<Uint8Array>> => {
  const stream = b.stream.GenerateEstimate(
    project_name,
    description,
    requirements,
  );
  return Promise.resolve(stream.toStreamable());
};