/*************************************************************************************************

Welcome to Baml! To use this generated code, please run one of the following:

$ npm install @boundaryml/baml
$ yarn add @boundaryml/baml
$ pnpm add @boundaryml/baml

*************************************************************************************************/

// This file was generated by BAML: do not edit it. Instead, edit the BAML
// files and re-generate this code.
//
/* eslint-disable */
// tslint:disable
// @ts-nocheck
// biome-ignore format: autogenerated code
'use server'

import { b } from '../index';
import type { Check, Checked  } from "../types";
import type { Image, Audio } from "@boundaryml/baml";

import type {  ConstructionProjectData,  EstimateLineItem,  InputFile } from "../types"

import type * as types from "../types"

/**
 * Regular BAML server actions that return direct responses.
 */

/**
 * Executes the "GenerateProjectEstimate" BAML action.
 *
 * This server action calls the underlying BAML function "GenerateProjectEstimate"
 * with the specified parameters.
 *
 * @param { string } project_assessment - Input parameter.
 *
 * @returns {Promise<ConstructionProjectData>} A promise that resolves with the result of the action.
 */
export const GenerateProjectEstimate = async (
  project_assessment: string,
): Promise<ConstructionProjectData> => {
  return b.GenerateProjectEstimate(
    project_assessment,
  );
};

/**
 * Executes the "ProcessProjectFiles" BAML action.
 *
 * This server action calls the underlying BAML function "ProcessProjectFiles"
 * with the specified parameters.
 *
 * @param { string } project_info - Input parameter.
 * @param { InputFile[] } files - Input parameter.
 * @param { Image | null } img (optional) - Input parameter.
 *
 * @returns {Promise<string>} A promise that resolves with the result of the action.
 */
export const ProcessProjectFiles = async (
  project_info: string,
  files: InputFile[],
  img?: Image | null,
): Promise<string> => {
  return b.ProcessProjectFiles(
    project_info,
    files,
    img,
  );
};