/*************************************************************************************************

Welcome to Baml! To use this generated code, please run one of the following:

$ npm install @boundaryml/baml
$ yarn add @boundaryml/baml
$ pnpm add @boundaryml/baml

*************************************************************************************************/

// This file was generated by BAML: do not edit it. Instead, edit the BAML
// files and re-generate this code.
//
/* eslint-disable */
// tslint:disable
// @ts-nocheck
// biome-ignore format: autogenerated code
'use server'

import { b } from '../index';
import type { Check, Checked  } from "../types";
import type { Image, Audio } from "@boundaryml/baml";

import type {  ConstructionProjectData,  EstimateLineItem,  InputFile } from "../types"

import type * as types from "../types"

/**
 * Streaming BAML server actions that return ReadableStreams.
 */

/**
 * Executes the streaming variant of the "GenerateProjectEstimate" BAML action.
 *
 * This action initiates a streaming response by calling the corresponding
 * BAML stream function. The returned stream yields incremental updates.
 *
 * @param { string } project_assessment - Input parameter.
 *
 * @returns {ReadableStream<Uint8Array>} A stream that yields incremental updates from the action.
 */
export const GenerateProjectEstimate = async (
  project_assessment: string,
): Promise<ReadableStream<Uint8Array>> => {
  const stream = b.stream.GenerateProjectEstimate(
    project_assessment,
  );
  return Promise.resolve(stream.toStreamable());
};

/**
 * Executes the streaming variant of the "ProcessProjectFiles" BAML action.
 *
 * This action initiates a streaming response by calling the corresponding
 * BAML stream function. The returned stream yields incremental updates.
 *
 * @param { string } project_info - Input parameter.
 * @param { InputFile[] } files - Input parameter.
 *
 * @returns {ReadableStream<Uint8Array>} A stream that yields incremental updates from the action.
 */
export const ProcessProjectFiles = async (
  project_info: string,
  files: InputFile[],
): Promise<ReadableStream<Uint8Array>> => {
  const stream = b.stream.ProcessProjectFiles(
    project_info,
    files,
  );
  return Promise.resolve(stream.toStreamable());
};