/*************************************************************************************************

Welcome to Baml! To use this generated code, please run one of the following:

$ npm install @boundaryml/baml
$ yarn add @boundaryml/baml
$ pnpm add @boundaryml/baml

*************************************************************************************************/

// This file was generated by BAML: do not edit it. Instead, edit the BAML
// files and re-generate this code.
//
/* eslint-disable */
// tslint:disable
// @ts-nocheck
// biome-ignore format: autogenerated code
import type { Check, Checked  } from "../types";
import type { Image, Audio } from "@boundaryml/baml";

import type {  AllowedTypes,  AssisantMessage,  BamlChatThread,  ConstructionProjectData,  EstimateLineItem,  Event,  InputFile,  KeyFrame,  Patch,  PatchEstimateRequest,  PatchEstimateResponse,  PatchOperation,  PatchResult,  UpdateEstimateRequest,  UpdateEstimateResponse,  UserInput,  VideoAnalysis } from "../types"

import type * as types from "../types"
import type { partial_types }from "../partial_types";

export type StreamingServerTypes = {
  AnalyzeVideo: partial_types.VideoAnalysis,
  DetermineNextStep: partial_types.Event,
  GenerateProjectEstimate: partial_types.ConstructionProjectData,
  ParseLineItem: partial_types.EstimateLineItem,
  ProcessAudio: string,
}