/*************************************************************************************************

Welcome to Baml! To use this generated code, please run one of the following:

$ npm install @boundaryml/baml
$ yarn add @boundaryml/baml
$ pnpm add @boundaryml/baml

*************************************************************************************************/

// This file was generated by BAML: do not edit it. Instead, edit the BAML
// files and re-generate this code.
//
/* eslint-disable */
// tslint:disable
// @ts-nocheck
// biome-ignore format: autogenerated code
import type { Image, Audio } from "@boundaryml/baml"
import type { Checked, Check } from "./types"
import type {  ConstructionProjectData,  EstimateLineItem,  InputFile } from "./types"
import type * as types from "./types"

/******************************************************************************
*
*  These types are used for streaming, for when an instance of a type
*  is still being built up and any of its fields is not yet fully available.
*
******************************************************************************/

export interface StreamState<T> {
    value: T
    state: "Pending" | "Incomplete" | "Complete"
}

export namespace partial_types {
    
    export interface ConstructionProjectData {
        project_description?: (string | null)
        estimated_total_min: ((number | null) | null)
        estimated_total_max: ((number | null) | null)
        estimated_timeline_days: ((number | null) | null)
        key_considerations?: (string | null)[]
        confidence_level?: (string | null)
        estimate_items?: (partial_types.EstimateLineItem | null)[]
        next_steps?: (string | null)[]
        missing_information?: (string | null)[]
        key_risks?: (string | null)[]
    }
    
    export interface EstimateLineItem {
        description?: (string | null)
        category?: (string | null)
        subcategory: ((string | null) | null)
        cost_range_min?: (number | null)
        cost_range_max?: (number | null)
        unit: ((string | null) | null)
        quantity: ((number | null) | null)
        assumptions: ((string | null) | null)
        confidence_score: ((string | null) | null)
        notes: ((string | null) | null)
    }
    
    export interface InputFile {
        name?: (string | null)
        type?: (string | null)
        description: ((string | null) | null)
        content: ((string | null) | null)
        download_url: ((string | null) | null)
        image_data: ((Image | null) | null)
    }
    
}