/*************************************************************************************************

Welcome to Baml! To use this generated code, please run one of the following:

$ npm install @boundaryml/baml
$ yarn add @boundaryml/baml
$ pnpm add @boundaryml/baml

*************************************************************************************************/

// This file was generated by BAML: do not edit it. Instead, edit the BAML
// files and re-generate this code.
//
/* eslint-disable */
// tslint:disable
// @ts-nocheck
// biome-ignore format: autogenerated code
import type { Image, Audio } from "@boundaryml/baml"
import type { Checked, Check } from "./types"
import type {  AllowedTypes,  AssisantMessage,  BamlChatThread,  ConstructionProjectData,  EstimateLineItem,  Event,  InputFile,  KeyFrame,  Patch,  PatchEstimateRequest,  PatchEstimateResponse,  PatchOperation,  PatchResult,  ResponseEvent,  UpdateEstimateRequest,  UpdateEstimateResponse,  UserInput,  VideoAnalysis } from "./types"
import type * as types from "./types"

/******************************************************************************
*
*  These types are used for streaming, for when an instance of a type
*  is still being built up and any of its fields is not yet fully available.
*
******************************************************************************/

export interface StreamState<T> {
    value: T
    state: "Pending" | "Incomplete" | "Complete"
}

export namespace partial_types {
    
    export interface AssisantMessage {
        message?: (string | null)
    }
    
    export interface BamlChatThread {
        events?: (partial_types.Event | null)[]
    }
    
    export interface ConstructionProjectData {
        project_description?: (string | null)
        estimated_total_min: ((number | null) | null)
        estimated_total_max: ((number | null) | null)
        estimated_timeline_days: ((number | null) | null)
        key_considerations?: (string | null)[]
        confidence_level?: (string | null)
        estimate_items?: (partial_types.EstimateLineItem | null)[]
        next_steps?: (string | null)[]
        missing_information?: (string | null)[]
        key_risks?: (string | null)[]
    }
    
    export interface EstimateLineItem {
        uid?: (string | null)
        description?: (string | null)
        category?: (string | null)
        subcategory: ((string | null) | null)
        cost_range_min?: (number | null)
        cost_range_max?: (number | null)
        unit: ((string | null) | null)
        quantity: ((number | null) | null)
        assumptions: ((string | null) | null)
        confidence_score: ((string | null) | null)
        notes: ((string | null) | null)
    }
    
    export interface Event {
        type?: (AllowedTypes | null)
        data?: ((partial_types.UserInput | null) | (partial_types.AssisantMessage | null) | (partial_types.UpdateEstimateRequest | null) | (partial_types.UpdateEstimateResponse | null) | (partial_types.PatchEstimateRequest | null) | (partial_types.PatchEstimateResponse | null) | null)
    }
    
    export interface InputFile {
        name?: (string | null)
        type?: (string | null)
        description: ((string | null) | null)
        content: ((string | null) | null)
        download_url: ((string | null) | null)
        image_data: ((Image | null) | null)
        audio_data: ((Audio | null) | null)
    }
    
    export interface KeyFrame {
        filename?: (string | null)
        timestamp_s?: (number | null)
        description?: (string | null)
    }
    
    export interface Patch {
        json_path?: (string | null)
        operation?: (PatchOperation | null)
        new_value?: (((string | null) | null) | (partial_types.EstimateLineItem | null) | null)
    }
    
    export interface PatchEstimateRequest {
        patches?: (partial_types.Patch | null)[]
    }
    
    export interface PatchEstimateResponse {
        patch_results?: (partial_types.PatchResult | null)[]
    }
    
    export interface PatchResult {
        success?: (boolean | null)
        error_message: ((string | null) | null)
    }
    
    export interface ResponseEvent {
        type?: (AllowedTypes | null)
        data?: ((partial_types.AssisantMessage | null) | (partial_types.UpdateEstimateRequest | null) | (partial_types.PatchEstimateRequest | null) | null)
    }
    
    export interface UpdateEstimateRequest {
        changes_to_make?: (string | null)
    }
    
    export interface UpdateEstimateResponse {
        success?: (boolean | null)
        error_message?: (string | null)
    }
    
    export interface UserInput {
        message?: (string | null)
    }
    
    export interface VideoAnalysis {
        detailed_description?: (string | null)
        key_frames?: (partial_types.KeyFrame | null)[]
    }
    
}