/*************************************************************************************************

Welcome to Baml! To use this generated code, please run one of the following:

$ npm install @boundaryml/baml
$ yarn add @boundaryml/baml
$ pnpm add @boundaryml/baml

*************************************************************************************************/

// This file was generated by BAML: do not edit it. Instead, edit the BAML
// files and re-generate this code.
//
/* eslint-disable */
// tslint:disable
// @ts-nocheck
// biome-ignore format: autogenerated code
import type { Image, Audio } from "@boundaryml/baml"
import type { Checked, Check } from "./types"
import type {  ContractorEstimate,  LineItem,  Milestone,  TimelineInfo } from "./types"
import type * as types from "./types"

/******************************************************************************
*
*  These types are used for streaming, for when an instance of a type
*  is still being built up and any of its fields is not yet fully available.
*
******************************************************************************/

export interface StreamState<T> {
    value: T
    state: "Pending" | "Incomplete" | "Complete"
}

export namespace partial_types {
    
    export interface ContractorEstimate {
        project_name?: (string | null)
        description?: (string | null)
        total_cost?: (number | null)
        line_items?: (partial_types.LineItem | null)[]
        estimated_hours?: (number | null)
        timeline?: (partial_types.TimelineInfo | null)
    }
    
    export interface LineItem {
        description?: (string | null)
        cost?: (number | null)
        quantity?: (number | null)
    }
    
    export interface Milestone {
        name?: (string | null)
        date?: (string | null)
        completion_percentage?: (number | null)
    }
    
    export interface TimelineInfo {
        start_date?: (string | null)
        end_date?: (string | null)
        milestones?: (partial_types.Milestone | null)[]
    }
    
}