/*************************************************************************************************

Welcome to Baml! To use this generated code, please run one of the following:

$ npm install @boundaryml/baml
$ yarn add @boundaryml/baml
$ pnpm add @boundaryml/baml

*************************************************************************************************/

// This file was generated by BAML: do not edit it. Instead, edit the BAML
// files and re-generate this code.
//
/* eslint-disable */
// tslint:disable
// @ts-nocheck
// biome-ignore format: autogenerated code
import type { Image, Audio } from "@boundaryml/baml"

/**
 * Recursively partial type that can be null.
 *
 * @deprecated Use types from the `partial_types` namespace instead, which provides type-safe partial implementations
 * @template T The type to make recursively partial.
 */
export type RecursivePartialNull<T> = T extends object
    ? { [P in keyof T]?: RecursivePartialNull<T[P]> }
    : T | null;

export interface Checked<T,CheckName extends string = string> {
    value: T,
    checks: Record<CheckName, Check>,
}


export interface Check {
    name: string,
    expr: string
    status: "succeeded" | "failed"
}

export function all_succeeded<CheckName extends string>(checks: Record<CheckName, Check>): boolean {
    return get_checks(checks).every(check => check.status === "succeeded")
}

export function get_checks<CheckName extends string>(checks: Record<CheckName, Check>): Check[] {
    return Object.values(checks)
}
export interface ConstructionProjectData {
  project_description: string
  estimated_total_min?: number | null
  estimated_total_max?: number | null
  estimated_timeline_days?: number | null
  key_considerations: string[]
  confidence_level: string
  estimate_items: EstimateLineItem[]
  next_steps: string[]
  missing_information: string[]
  key_risks: string[]
  
}

export interface ContractorEstimate {
  project_name: string
  description: string
  total_cost: number
  line_items: LineItem[]
  estimated_hours: number
  timeline: TimelineInfo
  
}

export interface EstimateLineItem {
  description: string
  category: string
  subcategory?: string | null
  cost_range_min: number
  cost_range_max: number
  unit?: string | null
  quantity?: number | null
  assumptions?: string | null
  confidence_score?: string | null
  notes?: string | null
  
}

export interface InputFile {
  name: string
  type: string
  description?: string | null
  content?: string | null
  download_url?: string | null
  image_data?: Image | null
  
}

export interface LineItem {
  description: string
  cost: number
  quantity: number
  
}

export interface Milestone {
  name: string
  date: string
  completion_percentage: number
  
}

export interface TimelineInfo {
  start_date: string
  end_date: string
  milestones: Milestone[]
  
}
